[package]
name = "rust-gtk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk = { version = "0.4.8", package = "gtk4", features = ["v4_6"] }
dotenv = "0.15.0"
once_cell = "1.15.0"
