[package]
name = "rust-gtk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk = { version = "0.4.8", package = "gtk4", features = ["v4_6"] }
once_cell = "1.15.0"

[[bin]]
name = "basic"
path = "src/main.rs"

[[bin]]
name = "event-loop"
path = "event_loop/main.rs"

[[bin]]
name = "settings"
path = "settings/main.rs"

[[bin]]
name = "list-widget"
path = "list_widget/main.rs"

[[bin]]
name = "string-list"
path = "string_list/main.rs"

[[bin]]
name = "hello_world"
path = "hello_world/main.rs"
